application: opendatapress
version: 0-1-2
runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /apple-touch-icon-precomposed.png
  static_files: static/apple-touch-icon-precomposed.png
  upload: static/apple-touch-icon-precomposed.png

- url: /(robots\.txt|humans\.txt)
  static_files: static/\1
  upload: static/(robots\.txt|humans\.txt)

- url: /css
  static_dir: static/css

- url: /js
  static_dir: static/js

- url: /img
  static_dir: static/img

- url: /fonts
  static_dir: static/fonts

- url: /admin
  script: main.app
  secure: always
  login: admin

- url: /dashboard
  script: main.app
  secure: always

- url: /.*
  script: main.app

admin_console:
  pages:
  - name: Manage Users
    url: /admin/manage_users

  - name: Manage Data Sources
    url: /admin/manage_data_sources

  - name: Manage Data Views
    url: /admin/manage_data_views

  - name: Manage DataBase
    url: /admin/manage_database

  - name: Manage Search
    url: /admin/manage_search

  - name: Bulk Email
    url: /admin/bulk_email

libraries:

- name: webapp2
  version: "2.5.2"
  
- name: jinja2
  version: "2.6"